export enum RouterEnum {
  home = '',
  login = 'login',
  register = 'register',
  logout = 'logout',
  transactions = 'transactions',
  addTransaction = 'add-transaction',
  editTransaction = 'edit-transaction',
  detailTransaction = 'detail-transaction',
  deleteTransaction = 'delete-transaction',
  dataTransfer = 'data-transfer',
  settings = 'settings',
  changePassword = 'change-password',
  deleteAccount = 'deleteAccount',
  preferences = 'preferences',
}
