export enum EndPoints {
  auth = 'auth',
  register = 'register',
  login = 'login',
  logout = 'logout',
  autoLogin = 'auto-login',
  finance = 'finance',
  transaction = 'transaction',
  getDefaultExpenseCategories = 'get-default-expense-categories',
  getDefaultIncomeCategories = 'get-default-income-categories',
  getDefaultCurrency = 'get-default-currency',
  userPreferences = 'user-preferences',
  groupTransaction = 'group-transaction',
  user = 'user',
}
